config/routes.rb
MobileApp::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  scope "/api" do
    devise_for :users, defaults: { format: :json }

    resources :users, only: [:create]

    resources :museums, only: [:index, :show]

    resources :family_cards, only: [:show]

    resources :checkins, only: [:show, :create]

    get '/activities/upcoming', to: 'activities#upcoming'
    get '/activities/featured', to: 'activities#featured'
  end
end

app/models/museum.rb
class Museum
  include Mongoid::Document
  include Mongoid::Slug
  include Mongoid::Timestamps

  has_many :checkins, dependent: :delete
  has_many :activities, dependent: :delete

  field :name, type: String
  field :phone_number, type: String
  field :address, type: String
  field :borough, type: String
  field :site_url, type: String
  field :image_url, type: String
  field :hours, type: Array, default: []
  field :subway_lines, type: Array, default: []
  field :bus_lines, type: String
  field :additional_directional_info, type: String
  field :categories, type: Array, default: []
  field :wifi, type: Boolean
  field :handicap_accessible, type: Boolean
  field :hands_on_activity, type: Boolean
  field :description, type: String
  field :free_admission, type: Boolean
  field :suggested_donation, type: Boolean
  field :name_id, type: String, default:-> { slug }
  field :twitter, type: String
  field :facebook, type: String
  field :checkin_url, type: String

  slug do |museum|
    Museum.slug_format(museum.name)
  end

  validates_presence_of :name, :phone_number, :address, :borough,
  						          :site_url, :image_url, :hours, :categories

  validates_uniqueness_of :name

  before_save :remove_empty_hours, :sort_subway_lines
  before_update :assign_slug

  def sort_subway_lines
    sorted_subway_lines = []

    SUBWAY_LINES.each do |line|
      if self.subway_lines.include?(line)
        sorted_subway_lines.push(line)
        self.subway_lines = self.subway_lines - [line]
      end
    end

    sorted_subway_lines = sorted_subway_lines + self.subway_lines if !self.subway_lines.empty?

    self.subway_lines = sorted_subway_lines
  end

  def self.slug_format(name)
    name.gsub(/[^A-Za-z0-9 ]/, '').split(" ").join("-").downcase
  end

  protected
  def remove_empty_hours
    self.hours.reject!(&:empty?)
  end

  def assign_slug
    self.slugs[0] = Museum.slug_format(self.name)
    self.name_id = self.slugs[0]
  end
end

app/controllers/museums_controller.rb
class MuseumsController < ApplicationController
  def index
    @museums = Museum.all
    expires_in 15.minutes
    fresh_when etag: @museums, last_modified: @museums.max(:updated_at), public: true
  end

  def show
    @museum = Museum.find(params[:id])
  end
end

app/helpers/museums_helper.rb
module MuseumsHelper
end

app/views/museums/_activity.html.erb
<li>
  <%= activity.name %> <%= "- #{activity.date}" if activity.date %>
  <%= ", #{activity.start_time} - #{activity.end_time}" if activity.start_time %>
  <p><%= activity.description %></p>
  <%= link_to 'Edit', edit_museum_activity_path(activity.museum, activity) %>
  <%= link_to 'Delete', museum_activity_path(activity.museum, activity), method: :delete, confirm: "Really delete #{activity.name}?" %>
</li>

app/views/museums/_form.html.erb
<%= simple_form_for(@museum, html: {class: 'form-vertical' }) do |f| %>
  <% if @museum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@museum.errors.count, "error") %> prohibited this museum from being saved:</h2>

      <ul>
      <% @museum.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :name %>
  <%= f.input :phone_number %>
  <%= f.input :address %>
  <%= f.input :borough, collection: ["Brooklyn", "Bronx", "Manhattan", "Queens", "Staten Island"], prompt: "Select a Borough" %>
  <%= f.input :site_url %>
  <%= f.input :image_url %>

  <div class="field">
    <%= label_tag :hours_1 %><br>
    <%= text_field_tag "museum[hours][]", @museum.hours[0] %>
  </div>
  <div class="field">
    <%= label_tag :hours_2 %><br>
    <%= text_field_tag "museum[hours][]", @museum.hours[1] %>
  </div>
  <div class="field">
    <%= label_tag :hours_3 %><br>
    <%= text_field_tag "museum[hours][]", @museum.hours[2] %>
  </div>
  <div class="field">
    <%= label_tag :hours_4 %><br>
    <%= text_field_tag "museum[hours][]", @museum.hours[3] %>
  </div>

  <%= label_tag "Subway Lines" %>
  <div class="field">
    <% Museum::SUBWAY_LINES.each do |line| %>
      <%= line %>
      <%= check_box_tag "museum[subway_lines][]", line,
       @museum.subway_lines.include?(line) ? true : false,
        include_hidden: false %>
    <% end %>
  </div>

  <%= f.input :bus_lines %>

  <%= f.input :additional_directional_info %>

  <%= label_tag "Categories" %>
  <div class="field">
    <% Museum::CATEGORIES.each do |category| %>
      <%= category %>
      <%= check_box_tag "museum[categories][]", category,
       @museum.categories.include?(category) ? true : false,
        include_hidden: false %>
    <% end %>
  </div>

  <div class="field">
      <%= f.label "Wifi" %> <br />
      <%= f.check_box :wifi %> <br />
  </div>

  <div class="field">
      <%= f.label "Handicap Accessible" %> <br />
      <%= f.check_box :handicap_accessible %> <br />
  </div>

  <div class="field">
      <%= f.label "Hands-On Activity" %> <br />
      <%= f.check_box :hands_on_activity %> <br />
  </div>

   <div class="field">
      <%= f.label "Free Admission" %> <br />
      <%= f.check_box :free_admission %> <br />
  </div>

   <div class="field">
      <%= f.label "Suggested Donation" %> <br />
      <%= f.check_box :suggested_donation %> <br />
  </div>

  <% if @museum.slug %>
    <p>
      <strong>Activities</strong>
      <ul>
        <% @museum.activities.each do   |activity| %>
          <%= render partial: 'activity', locals: {activity: activity} %>
        <% end %>
      </ul>
      <%= link_to 'New', new_museum_activity_path(@museum) %>
    </p>
  <% end %>

  <%= f.input :description, as: :text %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/museums/index.html.erb
<% if @warnings.present? %>
<div class="alert alert-warning fade in">
  <% @warnings.each do |warning|  %>
  <%= warning %><br>
  <% end %>
</div>
<% end %>

<h4>
  <%= link_to 'Go to Family Card Import', family_cards_path %>
</h4>

<h1>Listing museums</h1>
<div class="table-responsive">
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone Number</th>
      <th>Address</th>
      <th>Borough</th>
      <th>Website</th>
      <th>Image URL</th>
      <th>Hours</th>
      <th>Subwaylines</th>
      <th>Buslines</th>
      <th>Additional Directions</th>
      <th>Categories</th>
      <th>Has Wifi?</th>
      <th>Free Admission?</th>
      <th>Suggested Donation?</th>
      <th>Handicap Accessible?</th>
      <th>Hands-On Activity?</th>
      <th>Activities</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @museums.each do |museum| %>
      <tr>
        <td><%= museum.name %></td>
        <td><%= museum.phone_number %></td>
        <td><%= museum.address %></td>
        <td><%= museum.borough %></td>
        <td><%= museum.site_url %></td>
        <td><%= museum.image_url %></td>
        <td><%= museum.hours %></td>
        <td><%= museum.subway_lines %></td>
        <td><%= museum.bus_lines %></td>
        <td><%= museum.additional_directional_info %></td>
        <td><%= museum.categories %></td>
        <td><%= boolean_to_human(museum.wifi) %></td>
        <td><%= boolean_to_human(museum.free_admission) %></td>
        <td><%= boolean_to_human(museum.suggested_donation) %></td>
        <td><%= boolean_to_human(museum.handicap_accessible) %></td>
        <td><%= boolean_to_human(museum.hands_on_activity) %></td>
        <td><%= link_to 'Show', museum %></td>
        <td><%= link_to 'Edit', edit_museum_path(museum) %></td>
        <td><%= link_to 'Destroy', museum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

<%= link_to 'New Museum', new_museum_path %>


<h2>Import Museums</h2>

<%= form_tag import_museums_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import Museums" %>
<% end %>

app/views/museums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @museum.name %>
</p>

<p>
  <strong>Phonenumber:</strong>
  <%= @museum.phone_number %>
</p>

<p>
  <strong>Address:</strong>
  <%= @museum.address %>
</p>

<p>
  <strong>Borough:</strong>
  <%= @museum.borough %>
</p>

<p>
  <strong>Website:</strong>
  <%= @museum.site_url %>
</p>

<p>
  <strong>Image URL:</strong>
  <%= @museum.image_url %>
</p>

<p>
  <strong>Hours:</strong>
  <%= @museum.hours %>
</p>

<p>
  <strong>Subwaylines:</strong>
  <%= @museum.subway_lines %>
</p>

<p>
  <strong>Buslines:</strong>
  <%= @museum.bus_lines %>
</p>

<p>
  <strong>Categories:</strong>
  <%= @museum.categories %>
</p>

<p>
  <strong>Wifi?</strong>
  <%= boolean_to_human(@museum.wifi) %>
</p>

<p>
  <strong>Free Admission?</strong>
  <%= boolean_to_human(@museum.free_admission) %>
</p>

<p>
  <strong>Suggested Donation?</strong>
  <%= boolean_to_human(@museum.suggested_donation) %>
</p>

<p>
  <strong>Handicap Accessible?</strong>
  <%= boolean_to_human(@museum.handicap_accessible) %>
</p>

<p>
  <strong>Hands-On Activity?</strong>
  <%= boolean_to_human(@museum.hands_on_activity) %>
</p>

<p>
  <strong>Activities</strong>
  <ul>
    <% @museum.activities.each do   |activity| %>
      <%= render partial: 'activity', locals: {activity: activity} %>
    <% end %>
  </ul>
  <%= link_to 'New', new_museum_activity_path(@museum) %>
</p>

<p>
  <strong>Description:</strong>
  <%= @museum.description %>
</p>

<%= link_to 'Edit', edit_museum_path(@museum) %> |
<%= link_to 'Back', museums_path %>